export default [
  {
    name: "最新应用",
    siteList: [
      {
        icon: "icon-1.png",
        name: "磁力云",
        desc: "急速下载和在线观看...",
        url: "https://www.appboluo.com/app/636.html/",
      },
      {
        icon: "icon-2.png",
        name: "视频转换器",
        desc: "视频转换+压缩",
        url: "https://www.appboluo.com/app/614.html/",
      },
      {
        icon: "icon-3.png",
        name: "云盘钥匙",
        desc: "破解网盘提取码...",
        url: "https://www.appboluo.com/app/642.html/",
      },
      {
        icon: "icon-4.png",
        name: "语音导出",
        desc: "QQ，微信，公众号语音导出...",
        url: "https://www.appboluo.com/app/664.html/",
      },
      {
        icon: "icon-5.jpg",
        name: "万年历查询表",
        desc: "万年历查询好帮手...",
        url: "https://www.appboluo.com/app/807.html/",
      },
      {
        icon: "icon-6.png",
        name: "全局负一屏",
        desc: "这是一个可以在任何应用界面...",
        url: "https://www.appboluo.com/app/802.html/",
      },
      {
        icon: "icon-7.png",
        name: "舞图帮",
        desc: "如果你想配一台pc电脑，奈何...",
        url: "https://www.appboluo.com/app/785.html/",
      },
      {
        icon: "icon-8.png",
        name: "卡吧加钱党",
        desc: "急速下载和在线观看...",
        url: "https://www.appboluo.com/app/749.html/",
      },
      {
        icon: "icon-9.png",
        name: "隐私计算器",
        desc: "长按标题就可以进入第二空间...",
        url: "https://www.appboluo.com/app/741.html/",
      },
      {
        icon: "icon-10.png",
        name: "清风",
        desc: "一个多功能实用工具箱...",
        url: "https://www.appboluo.com/app/737.html/",
      },
    ],
  },
  {
    name: "资源搜索",
    siteList: [
      {
        icon: "icon-2-1.png",
        name: "百度网盘资源索引",
        desc: "【网盘搜索】收录了大量的网盘搜索...",
        url: "https://jdapk.com/sites/2278.html",
      },
      {
        icon: "icon-2-2.png",
        name: "各大网盘搜索资源",
        desc: "各大网盘搜索资源",
        url: "https://jdapk.com/sites/2276.html#",
      },
      {
        icon: "icon-2-3.png",
        name: "超能搜",
        desc: "超能搜搜索引擎搜录了数十款...",
        url: "https://www.chaonengsou.com/",
      },
      {
        icon: "icon-2-4.png",
        name: "万网搜",
        desc: "万网搜搜索引擎收录了数十款百度网...",
        url: "https://www.wanwangsou.com/?ref=jdapk.com",
      },
      {
        icon: "icon-2-5.png",
        name: "懒盘搜索",
        desc: "阿里云搜索网盘...",
        url: "https://lzpan.com/?ref=jdapk.com",
      },
      {
        icon: "icon-2-6.png",
        name: "阿里云资源合集",
        desc: "收集阿里云盘相关资源的论坛...",
        url: "https://jdapk.com/sites/2268.html",
      },
      {
        icon: "icon-2-7.png",
        name: "飞鱼盘搜索",
        desc: "质量不错的百度云搜索站，链接比较新...",
        url: "https://feiyu100.cn/",
      },
      {
        icon: "icon-2-8.png",
        name: "乌鸦搜",
        desc: "专注网盘的搜索引擎",
        url: "https://www.wuyasou.com/",
      },
      {
        icon: "icon-2-9.png",
        name: "毕方铺",
        desc: "更新及时，简洁的百度网盘资源搜索...",
        url: "https://www.iizhi.cn/",
      },
      {
        icon: "icon-2-10.png",
        name: "电影天堂",
        desc: "为广大网友提供最新的720p...",
        url: "https://dianyingtiantang.me/",
      },
    ],
  },
  {
    name: "便民查询",
    siteList: [
      {
        icon: "icon-3-1.png",
        name: "虫部落快搜",
        desc: "在互联网资源搜索，可谓重中之重...",
        url: "https://search.chongbuluo.com/",
      },
      {
        icon: "icon-3-2.png",
        name: "全球最牛的三大搜书网站",
        desc: "全球最牛的三大搜书网站",
        url: "https://zh.jp1lib.org/",
      },
      {
        icon: "icon-3-3.png",
        name: "查看自己的IP地址",
        desc: "检测你自己的IP地址和DNS地址",
        url: "https://jdapk.com/go/?url=aHR0cHM6Ly93aG9lci5uZXQvemg%3D",
      },
      {
        icon: "icon-3-4.png",
        name: "电子书下载导航",
        desc: "最好的电子书下载导航",
        url: "https://shuxiangjia.cn/",
      },
      {
        icon: "icon-3-5.png",
        name: "全国报刊杂志大全在线看",
        desc: "在线提供全国报纸...",
        url: "http://www.53bk.com/baokan/?ref=jdapk.com",
      },
      {
        icon: "icon-3-6.png",
        name: "IP地址查询-IPIP.NET",
        desc: "地址查询...",
        url: "http://www.ipip.net/ip.html",
      },
      {
        icon: "icon-3-7.png",
        name: "查快递",
        desc: "一键查快递",
        url: "https://www.kuaidi.com/",
      },
      {
        icon: "icon-3-8.png",
        name: "照片位置查询",
        desc: "照片位置查询",
        url: "https://www.gaitubao.com/exif",
      },
      {
        icon: "icon-3-9.png",
        name: "中国大学排名查询",
        desc: "中国大学排名查询",
        url: "https://daxue.911cha.com/",
      },
      {
        icon: "icon-3-10.png",
        name: "查节假日-万年历查询",
        desc: "万年历查询及节假日查询服务",
        url: "https://qq.ip138.com/day/",
      },
    ],
  },
  {
    name: "在线工具",
    siteList: [
      {
        icon: "icon-4-1.png",
        name: "星光工具网",
        desc: "星光工具网为您提供json格式",
        url: "https://www.starrytools.com/",
      },
      {
        icon: "icon-4-2.png",
        name: "简历制作",
        desc: "收录简历制作的相关站点",
        url: "https://jdapk.com/sites/2513.html",
      },
      {
        icon: "icon-4-3.png",
        name: "免费80种格式在线转换",
        desc: "种格式在线转换",
        url: "https://www.online-convert.com/",
      },
      {
        icon: "icon-4-4.png",
        name: "67tool-即时工具",
        desc: "67tool网页设计美观",
        url: "https://www.67tool.com/",
      },
      {
        icon: "icon-4-5.png",
        name: "新东方精品网课公开",
        desc: "白嫖新东方精品网课...",
        url: "http://www.nlc.cn/dsb_zyyfw/sytc/sp/",
      },
      {
        icon: "icon-4-6.png",
        name: "搜索收听和下载",
        desc: "全网所有的音乐都在这里...",
        url: "http://tools.liumingye.cn/music/?page=searchPage",
      },
      {
        icon: "icon-4-7.png",
        name: "爱给网-专注免费素材",
        desc: "中国最大的数字娱乐免费素材下载",
        url: "https://www.aigei.com/",
      },
      {
        icon: "icon-4-8.png",
        name: "在线免费图片编辑",
        desc: "在线免费图片编辑",
        url: "https://photofunia.com/cn",
      },
      {
        icon: "icon-4-9.png",
        name: "文库下载助手",
        desc: "目前支持百度文库，道客巴巴",
        url: "https://imwcr.cn/api/GetDocumentText/",
      },
      {
        icon: "icon-4-10.png",
        name: "图查查-图片查版权",
        desc: "图查查-图片查版权",
        url: "https://chacha.so.com/home?src=tuiguang",
      },
    ],
  },
  {
    name: "在线影视",
    siteList: [
      {
        icon: "icon-5-1.png",
        name: "麻花视频",
        desc: "麻花视频",
        url: "https://www.mhyyy.com/?ref=jdapk.com",
      },
      {
        icon: "icon-5-2.png",
        name: "4K高清蓝光下载索引",
        desc: "4K高清蓝光下载索引",
        url: "https://jdapk.com/sites/2578.html",
      },
      {
        icon: "icon-5-3.png",
        name: "美日韩港剧资源网站索引",
        desc: "美日韩港剧资源网站索引",
        url: "https://jdapk.com/sites/2576.html",
      },
      {
        icon: "icon-5-4.png",
        name: "电影院",
        desc: "提供阿里云盘资源",
        url: "https://dianyingyuan.org/",
      },
      {
        icon: "icon-5-5.png",
        name: "注视影视",
        desc: "电影电视剧清晰度都很高...",
        url: "https://gaze.run/",
      },
      {
        icon: "icon-5-6.png",
        name: "BT吧",
        desc: "720|1080|4k超高清分辨率电影",
        url: "https://www.aibtba.com/",
      },
      {
        icon: "icon-5-7.png",
        name: "不卡美剧",
        desc: "一个可在线看美剧的网站",
        url: "https://www.520meiju.com/",
      },
      {
        icon: "icon-5-8.png",
        name: "港剧网",
        desc: "为港剧迷提供在线看港剧",
        url: "https://www.bjbit.net/",
      },
      {
        icon: "icon-5-9.png",
        name: "大鱼TV",
        desc: "一家提供免费高清资源的网站",
        url: "https://ilqtugu.cn/",
      },
      {
        icon: "icon-5-10.png",
        name: "磁力天堂-超清蓝光",
        desc: "磁力天堂-超清蓝光",
        url: "https://www.ciligod.com/",
      },
    ],
  },
];
